const songLyrics = [
  "You’re kind of amazing like a time machine.",
  "The Digital Buddha is coming for you.",
  "On my tricycle, I’m in heaven. She’s my tricycle, I’m her melon.",
  "My ship at sail can climb a mountain, ride it to the sky.",
  "You look like someone I know, where did I meet you and where do we go?",
  "And hope fuels generations. And hope can start your car. And hope is the root of fantasy. Its nothing but a star.",
  "Hope is a generation. Bang your head in the car. And what is the root of fantasy? Lay your bet on a star",
  "And I found peace on the waiting room floor.",
  "You make me feel alive, like a parachute in the sky.",
  "Welcome to the crazy part of town. We like to take your life and turn it upside down",
  "In the shadow of the digital buddha are the countless wise, to bring you inspiration that you cannot buy.",
  "In the shadow of the digital buddha are the countless wise, to lift our generation to the highest high.",
  "Cheers to you it's like a dream you live by seeking fortunes at the door",
  "Baby I'm in space when I'm with you... Floating around nothing to do, maybe we can take a walk on the moon",
  "I can see it in your eyes, that you don't know what to say. I say goodbye, and walk away",
  "Cause tonight we can't do anything wrong",
  "Take me down to 34th street, where The Disco Biscuits are the king of the beat.",
  "Is there a pot of gold, at the end of this sweet rainbow?",
  "Always knew my home was in paradise.",
  "Hey little baby, now the morning's here. Gonna open my eyes, don't disappear.",
  "I thought it was the story of the world",
  "And in one day, he went from his cell to the sky - at his last chance to fly",
  "Just give me one more try, to chase down my dream, before I am done",
  "All was left, one chance to fly away",
  "I lived a life in shambles with one idea left to scheme, but if I ever built it - then what would i have left to dream",
  "Life, he said, is all about style",
  "Nowhere to kick us out - you've got the meaning all confused",
  "Break down the core reactor. Blown all to pieces for the new",
  "Sitting on a mountain top fifteen miles above the city.  Sitting in this melting pot where you can see the future with me",
  "My girl she left, so the story goes, what do you know? All the things i thought that i knew went out the window",
  "And maybe all that you want to be is all that you had to be",
  "Let me play you one that will make you howl",
  "Let me play you one that will make you wanna go out and jam!",
  "And the city boy is out of his mind again"
]

export default songLyrics;
